parameters:
    # Paramètres globaux
    upload_dir: '%kernel.project_dir%/public/uploads'

services:

    # Configuration par défaut pour les services de ce fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans les services.
        autoconfigure: true # Enregistre automatiquement les services comme commandes, etc.

    # Enregistre toutes les classes dans le dossier src/ comme services
    # Cela crée un service par classe dont l'identifiant est le FQCN
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    
        
    
    


    # Définition explicite des services nécessaires
    App\Service\ImageUploader:
        arguments:
            $uploadDir: '%upload_dir%'

    # Exemple d'autres services si nécessaires
    # App\Service\AnotherService:
    #     arguments:
    #         $someParameter: 'some_value'
